[workspace]
members = ["crates/*"]

[workspace.dependencies]
teamim = { path = "." }
eyre = "0.6.12"
color-eyre = "0.6"
thiserror = "2.0.11"
clap = { version = "4.5.26", features = ["derive"] }
phf = { version = "0.13", features = ["macros"] }
itertools = "0.14.0"
image = { version = "0.25.8", default-features = false }
rayon = "1.10.0"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_safety_doc = "allow"
missing_panics_doc = "allow"
needless_continue = "allow"

[package]
name = "teamim"
version = "0.1.0"
edition = "2024"

[features]
test_utils = ["image/default-formats"]

[dependencies]
clap.workspace = true
eyre.workspace = true
color-eyre.workspace = true
phf.workspace = true
thiserror.workspace = true
image.workspace = true
rayon.workspace = true
similar = { version = "2.7.0", features = ["unicode"] }
serde = { version = "1.0.217", features = ["derive"] }
search = { version = "0.1.0", path = "crates/search" }
tesseract-sys = "0.6.3"
tracing = "0.1.41"
blake3 = "1.8.5"
fastcdc = { version = "0.1.0", path = "crates/fastcdc" }
memmap2 = "0.9.11"
rkyv = "0.8.18"

[dev-dependencies]
image = { workspace = true, default-features = true }

[lints]
workspace = true

# [patch.crates-io]
# iced = { path = "../third-party/iced", version = "0.14.0" }
# iced_core = { path = "../third-party/iced/core", version = "0.14.0" }
# iced_graphics = { path = "../third-party/iced/graphics", version = "0.14.0" }
# iced_widget = { path = "../third-party/iced/widget", version = "0.14.0" }
