[package]
name = "sort_recogs"
version = "0.1.0"
edition = "2024"

[dependencies]
teamim = { path = "../.." }
clap = { workspace = true }
eyre = {workspace = true}
color-eyre = { workspace = true }
rayon = "1.10.0"
indicatif = { version = "0.17.11", features = ["rayon"] }
ctrlc = "3.4.5"
similar = "2.7.0"
maud = "0.27.0"

[lints]
workspace = true
