[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
image = "0.25.6"
rfd = "0.15.4"
smallvec = "1.15.1"
teamim = { version = "0.1.0", path = "../.." }
tracing = "0.1.41"
xilem = { git = "https://github.com/linebender/xilem", rev = "4823145e1756ff5773f5c2bfc24322e04e06fa93" }

[lints]
workspace = true
