[package]
name = "process-mam"
version = "0.1.0"
edition = "2024"

[dependencies]
mixup.workspace = true
reqwest = { version = "0.12.12", features = ["stream"] }
tokio = { version = "1.43.0", features = ["full"] }
clap = { workspace = true }
quick-xml = { version = "0.38", features = ["async-tokio"] }
futures = "0.3.31"
tokio-util = { version = "0.7.13", features = ["compat"] }
phf = { workspace = true }

[lints]
workspace = true
