[target.x86_64-pc-windows-msvc]
rustflags = [
    # this is needed for tesseract, for some reason
    "-C", "link-args=user32.lib crypt32.lib advapi32.lib",
    # "-C", "target-feature=+crt-static"
]
