[package]
name = "txt2img"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre.workspace = true
color-eyre.workspace = true
clap.workspace = true
teamim = { path = "../.." }
ab_glyph = "0.2.29"
tiff = "0.9.1"
indicatif = { version = "0.17.11", features = ["rayon"] }
imageproc = "0.25.0"
rand = "0.9.1"
rayon = "1.10.0"


[lints]
workspace = true
