[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = { workspace = true }
color-eyre = { workspace = true }
thiserror = { workspace = true }
axum = { version = "0.8.1", features = ["macros", "tower-log", "multipart"] }
teamim = { path = "../.." }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
serde = { version = "1.0.217", features = ["derive"] }
open = "5.3.2"
bytes = "1.9.0"
mime = "0.3.17"
maud = { version = "0.27.0", features = ["axum"] }
tower = "0.5.2"
tracing-appender = "0.2.3"
tracing-error = "0.2.1"
tracing = "0.1.41"

[dev-dependencies]
insta = "1.42.1"
