[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
teamim.workspace = true
eyre.workspace = true
image = { workspace = true, default-features = true }
derive_setters = "0.1.8"
lyon_algorithms = "1.0.16"
rfd = "0.16"
swash = "0.2.6"
tap = "1.0.1"
tokio = { version = "1.47.1", features = ["macros", "rt"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-error = "0.2.1"
color-eyre.workspace = true
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
bytes = "1.11.0"
iced_aw = { version = "0.13.0", default-features = false, features = ["color_picker", "number_input"] }
iced = { version = "0.14", features = ["advanced", "canvas", "image", "tokio", "wgpu"] }

[dev-dependencies]
teamim = { workspace = true, features = ["test_utils"] }
iced = { version = "0.14", features = ["debug"] }

[lints]
workspace = true
