[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
cosmic-text = "0.14.2"
derive_setters = "0.1.8"
eyre.workspace = true
iced = { version = "0.14.0-dev", path = "../../../iced", features = ["advanced", "canvas", "image", "tokio", "wgpu"] }
image = { version = "0.25.8", features = ["default-formats"] }
lyon_algorithms = "1.0.16"
num-traits = "0.2.19"
rfd = "0.15.4"
teamim = { version = "0.1.0", path = "../.." }
tokio = { version = "1.47.1", features = ["macros", "rt"] }

[dev-dependencies]
iced = { version = "0.14.0-dev", path = "../../../iced", features = ["debug"] }

[lints]
workspace = true
